[build]
  # Tell Netlify where your functions live
  functions = "netlify/functions"
  # We only need to install deps in our functions folder
  command   = "npm install && cd netlify/functions && npm install"
  # We’re not publishing a static site; it’s a proxy only
  publish   = "/"

# (no plugins needed beyond this point)
