# netlify.toml
[build]
  # Point Netlify at your Lambda directory
  functions = "netlify/functions"

  # ONLY install deps in that folder
  command = "cd netlify/functions && npm install"

  # We're not serving any static files here
  publish = "/"
